### ISSUE TITLE
"NoClassDefFoundError FsInput" error

### ISSUE THREAD

**Issue by H4ml3t** [databricks/spark-avro#45]
_Update: please read my second post_

---

I'm using (~ desperately trying to use) the 1.0.0 version, since with the previous one I have the "LONG not supported error".

```
<dependency>
   <groupId>com.databricks</groupId>
   <artifactId>spark-avro_2.10</artifactId>
   <version>1.0.0</version>
</dependency>
```

In Eclipse I got this error
_"bad symbolic reference. A signature in package.class refers to type DataFrame in package org.apache.spark.sql which is not available. It may be completely missing from the current classpath, or the version on the classpath might be incompatible with the version used when compiling package.class."_
As well with spark-shell --jars 

```
scala>     val sqlContext = new org.apache.spark.sql.SQLContext(sc)
sqlContext: org.apache.spark.sql.SQLContext = org.apache.spark.sql.SQLContext@7d942108
scala> import com.databricks.spark.avro._
import com.databricks.spark.avro._
scala> sqlContext.avroFile(pathToAvrodata).collect().foreach(println)
error: bad symbolic reference. A signature in package.class refers to type DataFrame
in package org.apache.spark.sql which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
```

Moreover with the previous version I was able to "package with maven" now not anymore:

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.3:compile (default) on project spark-formats-test: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.3:compile (default) on project spark-formats-test: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1)
```

I'm using Eclipse Kepler, maven 3.0+ and Scala plugin 2.10.4 with the net.alchim31.maven to compile the Scala project. Any help or suggestion is really appreciated.

Cheers,
L

**Comment by H4ml3t** [comment]
OK, I've just found out that I should use the 0.2.0 version with the spark version I'm using (1.2.0), but the problem now is even more scary
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/avro/mapred/FsInput
[...]
Caused by: java.lang.ClassNotFoundException: org.apache.avro.mapred.FsInput
```
But at least now I managed to compile with maven, AND I have the same problem submitting the jar with the command ```spark-submit```.

What I'm doing (both in the shell and in the jar is):

```
sqlContext.sql(s"CREATE TEMPORARY TABLE avroTable USING com.databricks.spark.avro OPTIONS (path "$pathToAvrodata")")
sqlContext.sql("SELECT * FROM avroTable").collect().foreach(println)
```
or alternatively
```
import com.databricks.spark.avro._
sqlContext.avroFile(pathToAvrodata).collect().foreach(println)
```
... but the result is the same.

Again, any suggestion? Am I overlooking something? :(
Thanks in advance,
Luca

**Comment by imlk** [comment]
I think you should add this:

<dependency>
	<groupId>org.apache.avro</groupId>
	<artifactId>avro-mapred</artifactId>
	<version>1.7.7</version>
</dependency>

**Comment by H4ml3t** [comment]
Hi, I have it.
The only problem may be that I'm using this repo:
```
<repositories>
	<repository>
		<id>cloudera-repo-releases</id>
		<url>https://repository.cloudera.com/artifactory/repo/</url>
	</repository>
</repositories>
```
I had to download the release v0.1 and correct the wrong "switch/case" inside the AvroRelation.scala object, since I was having the problem ```java.lang.RuntimeException: Unsupported type LONG```, like suggested in this [other issue](https://github.com/databricks/spark-avro/issues/1).
Whit this solution now everything seem to work, I can read avro file easily.
To recap (maybe can be useful for others), I am using:
* Eclipse Kepler with plugin scala plugin version 2.10.4 and net.alchim31.maven to compile
* groupId: org.apache.spark, artifactId: spark-core_2.10, version: 1.2.0-cdh5.3.1
* groupId: org.apache.spark, artifactId: spark-sql_2.10, version: 1.2.0-cdh5.3.1
* groupId: org.apache.avro, artifactId: avro, version: 1.7.7
* groupId: org.apache.avro, artifactId: avro-mapred, version: 1.7.7

Cheers!

**Comment by marmbrus** [comment]
Seem like this issue is resolved?

**Comment by H4ml3t** [comment]
Not really, because jar "spark-avro_2.10-0.2.0.jar" published by maven still contains this error.

**Comment by koertkuipers** [comment]
i just build spark 1.4.1 for hadoop 2.6 (CDH 5.4) and tried to use spark-avro:
```
bin/spark-shell --packages com.databricks:spark-avro_2.10:1.0.0
scala> val data = sqlContext.read.format("com.databricks.spark.avro").load("/my/data")
java.lang.NoClassDefFoundError: org/apache/avro/mapred/FsInput
	at com.databricks.spark.avro.AvroRelation.newReader(AvroRelation.scala:111)
	at com.databricks.spark.avro.AvroRelation.<init>(AvroRelation.scala:53)
	at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:41)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:269)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
```
am i supposed to add the avro dependencies myself?

**Comment by H4ml3t** [comment]
You are lucky that you can use spark 1.4.1, but you are doing it wrong.
According to the example:
```scala
import com.databricks.spark.avro._
val sqlContext = new SQLContext(sc)
val df = sqlContext.read.avro("src/test/resources/episodes.avro")
```

Coming back to the error, there will be any hope that the jar spark-avro_2.10-0.2.0.jar will be fixed?

Cheers,
Luca

**Comment by JoshRosen** [comment]
To clarify, are you asking us to provided a patched version which works with Spark 1.2.x? Or are there also problems with 1.4.x? Would be good to separate these concerns since they need to be fixed differently.

**Comment by H4ml3t** [comment]
The problem occurs only in Spark 1.2.X and it is due to the missing switch cases
```scala
case LONG => SchemaType(LongType, nullable = false)
case ENUM => SchemaType(StringType, nullable = false)
```
in AvroRelation.scala.
Thank you :dancer:

**Comment by dzolnai** [comment]
I had the same exception when using `Spark 1.3.1 CDH 5.4.2  Hadoop 2.6.0` version.
To fix it, I had to add the `1.6.3` version of the `avro-mapred` package:
`--packages com.databricks:spark-avro_2.10:1.0.0,org.apache.avro:avro-mapred:1.6.3`
Higher versions of the `avro-mapred` package were not compatible.

**Comment by JoshRosen** [comment]
I'm going to optimistically close this issue since I don't think that it affects current versions of this library or Spark.
